name: login_screen_homework
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  intl: ^0.17.0
  animated_text_kit: ^4.2.2
  dio: ^4.0.6
  path_provider: ^2.0.11
  dropdown_button2: ^1.9.2
  permission_handler: ^10.2.0
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  botton_nav_bar: ^1.0.2
  curved_navigation_bar: ^1.0.3
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^3.5.0
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.1
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.8.4
  http: ^1.1.0
  lottie: ^2.4.0
  image_picker: ^1.0.1
  modal_bottom_sheet: ^2.1.2
  zoom_tap_animation: ^1.1.0
  flutter_carousel_slider: ^1.1.0
  shimmer: ^3.0.0
  provider: ^6.0.5
  shared_preferences: ^2.0.0
  change_app_package_name: ^1.1.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/